"""baseline schema

Revision ID: 3c1e8d85825f
Revises: 
Create Date: 2026-02-19 23:38:06.386650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1e8d85825f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'parent_ott_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('parent_ott_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
